Allow users to contact support from Keycloak login page
Trihydro/keycloakify-starter pull request #1
Opened 2024-06-18 17:06 UTC by dmccoystephenson

## Problem
There is no way for users to contact support from the Keycloak login page at this time.

## Solution
The Login page has been modified to include some mailto: links to allow users to contact support if necessary.

## Testing
This has been tested on Trihydro's fork of the jpo-cvmanager project:

![image](https://github.com/Trihydro/keycloakify-starter/assets/21204351/30c9b8ed-6a7f-45cc-874b-f8abd2494ec2)

2024-07-02 14:55 UTC, mwodahl approved these changes
This worked well for me!

2024-07-08 20:03 UTC, payneBrandon commented on src/login/pages/Login.tsx
> +                <ul>
Is there a way to do this more dynamically? IE read from environment variables or config file or something so we can swap out per environment?

2024-07-08 20:03 UTC, payneBrandon requested changes
Just the one question

2025-03-25 22:26 UTC, dmccoystephenson commented on src/login/pages/Login.tsx
> +                <ul>
You can reference an environment variable when launching the Keycloakify starter with yarn storybook. However, when building the theme as a JAR and using it in the jpo-cvmanager project, passing the same environment variable to the cvmanager_webapp service doesn't seem to have the same effect. After spending some time troubleshooting, I've decided to revert my configurability changes and stick with hardcoded email links.

2025-08-29 18:00 UTC, payneBrandon approved these changes
lgtm

2025-08-29 18:01 UTC, merged